#!/bin/zsh

# Borrowed from grunt-cli
# http://gruntjs.com/
#
# Copyright (c) 2012 Tyler Kellen, contributors
# Licensed under the MIT license.
# https://github.com/gruntjs/grunt/blob/master/LICENSE-MIT

# Usage:
#
# To enable zsh <tab> completion for Assemble, add the following line (minus the
# leading #, which is the zsh comment character) to your ~/.zshrc file:
#
# eval "$(Assemble --completion=zsh)"

# Enable zsh autocompletion.
function _Assemble_completion() {
  # Grab tasks
  compls=$(Assemble --tasks-simple)
  completions=(${=compls})
  compadd -- $completions
}

compdef _Assemble_completion Assemble
